---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: {{ template "dev.fullname" . }}
  labels:
    app: {{ template "dev.name" . }}
    chart: {{ template "dev.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  metrics:
  - name: pass-always
    count: 2
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: alpine:3.8
                command: [sh, -c]
                args: [exit 0]
              restartPolicy: Never
          backoffLimit: 0